# Generated by Django 4.2.30 on 2026-06-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('folder', 'Folder'), ('leaf', 'Leaf')], max_length=10)),
                ('owner_object_id', models.PositiveIntegerField()),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_nodes_content', to='contenttypes.contenttype')),
                ('owner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_nodes_owned', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='document_tree.treenode')),
            ],
        ),
        migrations.CreateModel(
            name='NodeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('explicit', 'Explicit'), ('groupement_all', 'All pharmacies in groupement')], default='explicit', max_length=20)),
                ('shared_by_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('permission', models.CharField(default='read_only', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groupement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_shares', to='core.groupement')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='document_tree.treenode')),
                ('shared_by_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_targeted', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='treenode',
            index=models.Index(fields=['parent'], name='document_tr_parent__515118_idx'),
        ),
        migrations.AddIndex(
            model_name='treenode',
            index=models.Index(fields=['owner_content_type', 'owner_object_id'], name='document_tr_owner_c_39bacc_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeshare',
            index=models.Index(fields=['node'], name='document_tr_node_id_c424e8_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeshare',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='document_tr_target__38ec54_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeshare',
            index=models.Index(fields=['shared_by_content_type', 'shared_by_object_id'], name='document_tr_shared__585245_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeshare',
            index=models.Index(fields=['groupement'], name='document_tr_groupem_34bf19_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodeshare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('groupement__isnull', True), ('scope', 'explicit'), ('target_content_type__isnull', False), ('target_object_id__isnull', False)), models.Q(('groupement__isnull', False), ('scope', 'groupement_all'), ('target_content_type__isnull', True), ('target_object_id__isnull', True)), _connector='OR'), name='nodeshare_scope_consistency'),
        ),
    ]
